/* Auto-generated by genmsg_cpp for file /home/baram/ros/catkin_ws/src/rover5_ros/srv/rover5_node_cmd_pwm.srv */
#ifndef ROVER5_ROS_SERVICE_ROVER5_NODE_CMD_PWM_H
#define ROVER5_ROS_SERVICE_ROVER5_NODE_CMD_PWM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace rover5_ros
{
template <class ContainerAllocator>
struct rover5_node_cmd_pwmRequest_ {
  typedef rover5_node_cmd_pwmRequest_<ContainerAllocator> Type;

  rover5_node_cmd_pwmRequest_()
  : pwm_left(0)
  , pwm_right(0)
  {
  }

  rover5_node_cmd_pwmRequest_(const ContainerAllocator& _alloc)
  : pwm_left(0)
  , pwm_right(0)
  {
  }

  typedef int32_t _pwm_left_type;
  int32_t pwm_left;

  typedef int32_t _pwm_right_type;
  int32_t pwm_right;


  typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rover5_node_cmd_pwmRequest
typedef  ::rover5_ros::rover5_node_cmd_pwmRequest_<std::allocator<void> > rover5_node_cmd_pwmRequest;

typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmRequest> rover5_node_cmd_pwmRequestPtr;
typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmRequest const> rover5_node_cmd_pwmRequestConstPtr;



template <class ContainerAllocator>
struct rover5_node_cmd_pwmResponse_ {
  typedef rover5_node_cmd_pwmResponse_<ContainerAllocator> Type;

  rover5_node_cmd_pwmResponse_()
  : ret(0)
  {
  }

  rover5_node_cmd_pwmResponse_(const ContainerAllocator& _alloc)
  : ret(0)
  {
  }

  typedef int32_t _ret_type;
  int32_t ret;


  typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rover5_node_cmd_pwmResponse
typedef  ::rover5_ros::rover5_node_cmd_pwmResponse_<std::allocator<void> > rover5_node_cmd_pwmResponse;

typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmResponse> rover5_node_cmd_pwmResponsePtr;
typedef boost::shared_ptr< ::rover5_ros::rover5_node_cmd_pwmResponse const> rover5_node_cmd_pwmResponseConstPtr;


struct rover5_node_cmd_pwm
{

typedef rover5_node_cmd_pwmRequest Request;
typedef rover5_node_cmd_pwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct rover5_node_cmd_pwm
} // namespace rover5_ros

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f37351ae2031f4885433b8aa5d4d18d0";
  }

  static const char* value(const  ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf37351ae2031f488ULL;
  static const uint64_t static_value2 = 0x5433b8aa5d4d18d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover5_ros/rover5_node_cmd_pwmRequest";
  }

  static const char* value(const  ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 pwm_left\n\
int32 pwm_right\n\
\n\
";
  }

  static const char* value(const  ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3bd113e2f12c9c571d32a0bd71d59b8d";
  }

  static const char* value(const  ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3bd113e2f12c9c57ULL;
  static const uint64_t static_value2 = 0x1d32a0bd71d59b8dULL;
};

template<class ContainerAllocator>
struct DataType< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover5_ros/rover5_node_cmd_pwmResponse";
  }

  static const char* value(const  ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 ret\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pwm_left);
    stream.next(m.pwm_right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rover5_node_cmd_pwmRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rover5_node_cmd_pwmResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<rover5_ros::rover5_node_cmd_pwm> {
  static const char* value() 
  {
    return "c5ab5daf069941f8e4c889717b1678ff";
  }

  static const char* value(const rover5_ros::rover5_node_cmd_pwm&) { return value(); } 
};

template<>
struct DataType<rover5_ros::rover5_node_cmd_pwm> {
  static const char* value() 
  {
    return "rover5_ros/rover5_node_cmd_pwm";
  }

  static const char* value(const rover5_ros::rover5_node_cmd_pwm&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5ab5daf069941f8e4c889717b1678ff";
  }

  static const char* value(const rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover5_ros/rover5_node_cmd_pwm";
  }

  static const char* value(const rover5_ros::rover5_node_cmd_pwmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5ab5daf069941f8e4c889717b1678ff";
  }

  static const char* value(const rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rover5_ros/rover5_node_cmd_pwm";
  }

  static const char* value(const rover5_ros::rover5_node_cmd_pwmResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROVER5_ROS_SERVICE_ROVER5_NODE_CMD_PWM_H

