"""autogenerated by genpy from rover5_ros/rover5_node_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class rover5_node_msg(genpy.Message):
  _md5sum = "ad83e5b852ff7eb503e240cbde5519e0"
  _type = "rover5_ros/rover5_node_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 pwm_left
int32 pwm_right
int32 sonic_distance_left
int32 sonic_distance_right


"""
  __slots__ = ['pwm_left','pwm_right','sonic_distance_left','sonic_distance_right']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pwm_left,pwm_right,sonic_distance_left,sonic_distance_right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rover5_node_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pwm_left is None:
        self.pwm_left = 0
      if self.pwm_right is None:
        self.pwm_right = 0
      if self.sonic_distance_left is None:
        self.sonic_distance_left = 0
      if self.sonic_distance_right is None:
        self.sonic_distance_right = 0
    else:
      self.pwm_left = 0
      self.pwm_right = 0
      self.sonic_distance_left = 0
      self.sonic_distance_right = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.pwm_left, _x.pwm_right, _x.sonic_distance_left, _x.sonic_distance_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.pwm_left, _x.pwm_right, _x.sonic_distance_left, _x.sonic_distance_right,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.pwm_left, _x.pwm_right, _x.sonic_distance_left, _x.sonic_distance_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.pwm_left, _x.pwm_right, _x.sonic_distance_left, _x.sonic_distance_right,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
